//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import Foundation

protocol ___VARIABLE_VIPERSTACKNAME___InteractorProtocol {
	
}

final class ___VARIABLE_VIPERSTACKNAME___Interactor {
    private let dependencies: ___VARIABLE_VIPERSTACKNAME___InteractorDependenciesProtocol
    
    init(dependencies: ___VARIABLE_VIPERSTACKNAME___InteractorDependenciesProtocol) {
        self.dependencies = dependencies
    }
}

extension ___VARIABLE_VIPERSTACKNAME___Interactor: ___VARIABLE_VIPERSTACKNAME___InteractorProtocol {
	
}
